name: Retrieve files

on:
    workflow_call:

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v4
        with:
          path: /home/runner/work/paper-animate/paper-animate