name: Initiate npm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: npm init
      run: npm init -y
    - name: Push commits
      run: |
        git config user.email "you@example.com"
        git config user.name "funny bot"
        git add package.json
        git commit -m "Initiate npm"
        git push
