name: Initiate npm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: npm init
      run: npm init -y
  push:
    uses: ./.github/workflows/push.yml
