name: Push changes

on:
    workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Push commits
        run: |
          git config user.email "you@example.com"
          git config user.name "funny bot"
          git add package.json
          git commit -m "Initiate npm"
          git push