name: Shell

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install paper

        run: npm install paper
      - name: Retrieve files
        uses: actions/upload-artifact@v4
        with:
          path: /home/runner/work/paper-animate/paper-animate
  download:
    uses: ./.github/workflows/artifact.yml
