name: Makeshift command line

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Script
      run: |
        npm install jquery
      
    - name: Push commits
      run: |
        git config user.email "you@example.com"
        git config user.name "funny bot"
        git add --all
        git commit -m "Install jQuery"
        git push
